/** MOVER LEITURAS PARA NOVO INVENTARIO **/
UPDATE PDG010 SET PDG_CODIGO = 'NOVO CODIGO DE INVENTARIO'
WHERE PDG_CODIGO = 'CODIGO INVENTARIO ANTIGO'

/** RE FUNCIONARIO */
SELECT US.ID_USUARIO, LG.LOGIN, US.EMAIL, US.NOME, US.CENTRO_CUSTO, * FROM ACS_USUARIO US
INNER JOIN ACS_LOGIN LG ON LG.ID_LOGIN = US.ID_LOGIN
WHERE LG.RE_FUNCIONARIO = '000000';