USE [master]
GO

CREATE SERVER AUDIT [AUDITORIA_SEGURANCA]
TO FILE 
(	FILEPATH = N'A:\AUDIT\LGPD'
	,MAXSIZE = 500 MB
	,RESERVE_DISK_SPACE = OFF
) WITH (QUEUE_DELAY = 1000, ON_FAILURE = CONTINUE)
ALTER SERVER AUDIT [AUDITORIA_SEGURANCA] WITH (STATE = ON)
GO

CREATE SERVER AUDIT SPECIFICATION AUDITORIA_EVENTOS
FOR SERVER AUDIT AUDITORIA_SEGURANCA
ADD (DATABASE_PERMISSION_CHANGE_GROUP),  -- Mudan�a de permiss�es no banco
ADD (SERVER_ROLE_MEMBER_CHANGE_GROUP),   -- Altera��o em fun��es de servidor
ADD (AUDIT_CHANGE_GROUP),                -- Altera��es em auditorias
ADD (FAILED_LOGIN_GROUP),                -- Tentativas de login fracassadas
ADD (DATABASE_PRINCIPAL_CHANGE_GROUP)    -- Mudan�a em usu�rios do banco
WITH (STATE = ON);
GO

USE [programas]
GO

CREATE DATABASE AUDIT SPECIFICATION AUDITORIA_DML
FOR SERVER AUDIT AUDITORIA_SEGURANCA
ADD (SELECT, INSERT, UPDATE, DELETE ON ACS_LOGIN BY db_datareader),
ADD (SELECT, INSERT, UPDATE, DELETE ON ACS_LOGIN BY db_datawriter),
ADD (SELECT, INSERT, UPDATE, DELETE ON ACS_LOGIN BY db_ddladmin),
ADD (SELECT, INSERT, UPDATE, DELETE ON ACS_LOGIN BY db_executor),

ADD (SELECT, INSERT, UPDATE, DELETE ON ACS_USUARIO BY db_datareader),
ADD (SELECT, INSERT, UPDATE, DELETE ON ACS_USUARIO BY db_datawriter),
ADD (SELECT, INSERT, UPDATE, DELETE ON ACS_USUARIO BY db_ddladmin),
ADD (SELECT, INSERT, UPDATE, DELETE ON ACS_USUARIO BY db_executor),

ADD (SELECT, INSERT, UPDATE, DELETE ON CFG_EMAIL BY db_datareader),
ADD (SELECT, INSERT, UPDATE, DELETE ON CFG_EMAIL BY db_datawriter),
ADD (SELECT, INSERT, UPDATE, DELETE ON CFG_EMAIL BY db_ddladmin),
ADD (SELECT, INSERT, UPDATE, DELETE ON CFG_EMAIL BY db_executor),

ADD (SELECT, INSERT, UPDATE, DELETE ON CFG_SENHA BY db_datareader),
ADD (SELECT, INSERT, UPDATE, DELETE ON CFG_SENHA BY db_datawriter),
ADD (SELECT, INSERT, UPDATE, DELETE ON CFG_SENHA BY db_ddladmin),
ADD (SELECT, INSERT, UPDATE, DELETE ON CFG_SENHA BY db_executor),

ADD (SELECT, INSERT, UPDATE, DELETE ON SA1010 BY db_datareader),
ADD (SELECT, INSERT, UPDATE, DELETE ON SA1010 BY db_datawriter),
ADD (SELECT, INSERT, UPDATE, DELETE ON SA1010 BY db_ddladmin),
ADD (SELECT, INSERT, UPDATE, DELETE ON SA1010 BY db_executor),

ADD (SELECT, INSERT, UPDATE, DELETE ON SRA010 BY db_datareader),
ADD (SELECT, INSERT, UPDATE, DELETE ON SRA010 BY db_datawriter),
ADD (SELECT, INSERT, UPDATE, DELETE ON SRA010 BY db_ddladmin),
ADD (SELECT, INSERT, UPDATE, DELETE ON SRA010 BY db_executor),

ADD (SELECT ON VW_P5D_TAB_SRA010 BY db_datareader),
ADD (SELECT ON VW_P5D_TAB_SRA010 BY db_datawriter),
ADD (SELECT ON VW_P5D_TAB_SRA010 BY db_ddladmin),
ADD (SELECT ON VW_P5D_TAB_SRA010 BY db_executor),

ADD (SELECT ON VW_P5D_TAB_SA1010 BY db_datareader),
ADD (SELECT ON VW_P5D_TAB_SA1010 BY db_datawriter),
ADD (SELECT ON VW_P5D_TAB_SA1010 BY db_ddladmin),
ADD (SELECT ON VW_P5D_TAB_SA1010 BY db_executor),

ADD (SELECT ON UTL_PRODUTOS BY db_datareader),
ADD (SELECT ON UTL_PRODUTOS BY db_datawriter),
ADD (SELECT ON UTL_PRODUTOS BY db_ddladmin),
ADD (SELECT ON UTL_PRODUTOS BY db_executor),

ADD (SELECT ON UTL_FUNCIONARIOS BY db_datareader),
ADD (SELECT ON UTL_FUNCIONARIOS BY db_datawriter),
ADD (SELECT ON UTL_FUNCIONARIOS BY db_ddladmin),
ADD (SELECT ON UTL_FUNCIONARIOS BY db_executor),

ADD (SELECT ON UTL_CLIENTES BY db_datareader),
ADD (SELECT ON UTL_CLIENTES BY db_datawriter),
ADD (SELECT ON UTL_CLIENTES BY db_ddladmin),
ADD (SELECT ON UTL_CLIENTES BY db_executor),

ADD (SELECT ON VW_P5D_TAB_SB1010 BY db_datareader),
ADD (SELECT ON VW_P5D_TAB_SB1010 BY db_datawriter),
ADD (SELECT ON VW_P5D_TAB_SB1010 BY db_ddladmin),
ADD (SELECT ON VW_P5D_TAB_SB1010 BY db_executor)
WITH (STATE = ON);