USE [master]
GO

CREATE SERVER AUDIT [AUDITORIA_SEGURANCA]
TO FILE 
(	FILEPATH = N'E:\AUDIT\LGPD\'
	,MAXSIZE = 500 MB
	,RESERVE_DISK_SPACE = OFF
) WITH (QUEUE_DELAY = 1000, ON_FAILURE = CONTINUE)
ALTER SERVER AUDIT [AUDITORIA_SEGURANCA] WITH (STATE = ON)
GO

CREATE SERVER AUDIT SPECIFICATION AUDITORIA_EVENTOS
FOR SERVER AUDIT AUDITORIA_SEGURANCA
ADD (DATABASE_PERMISSION_CHANGE_GROUP),  -- Mudan�a de permiss�es no banco
ADD (SERVER_ROLE_MEMBER_CHANGE_GROUP),   -- Altera��o em fun��es de servidor
ADD (AUDIT_CHANGE_GROUP),                -- Altera��es em auditorias
ADD (FAILED_LOGIN_GROUP),                -- Tentativas de login fracassadas
ADD (DATABASE_PRINCIPAL_CHANGE_GROUP)    -- Mudan�a em usu�rios do banco
WITH (STATE = ON);
GO

USE [P5DADOS]
GO

CREATE DATABASE AUDIT SPECIFICATION AUDITORIA_DML
FOR SERVER AUDIT AUDITORIA_SEGURANCA
ADD (SELECT, INSERT, UPDATE, DELETE ON SE1010 BY db_datareader),
ADD (SELECT, INSERT, UPDATE, DELETE ON SE1010 BY db_datawriter),
ADD (SELECT, INSERT, UPDATE, DELETE ON SE1010 BY db_ddladmin),
ADD (SELECT, INSERT, UPDATE, DELETE ON SE1010 BY db_executor),

ADD (SELECT, INSERT, UPDATE, DELETE ON SE2010 BY db_datareader),
ADD (SELECT, INSERT, UPDATE, DELETE ON SE2010 BY db_datawriter),
ADD (SELECT, INSERT, UPDATE, DELETE ON SE2010 BY db_ddladmin),
ADD (SELECT, INSERT, UPDATE, DELETE ON SE2010 BY db_executor),

ADD (SELECT, INSERT, UPDATE, DELETE ON SE3010 BY db_datareader),
ADD (SELECT, INSERT, UPDATE, DELETE ON SE3010 BY db_datawriter),
ADD (SELECT, INSERT, UPDATE, DELETE ON SE3010 BY db_ddladmin),
ADD (SELECT, INSERT, UPDATE, DELETE ON SE3010 BY db_executor),

ADD (SELECT, INSERT, UPDATE, DELETE ON SF1010 BY db_datareader),
ADD (SELECT, INSERT, UPDATE, DELETE ON SF1010 BY db_datawriter),
ADD (SELECT, INSERT, UPDATE, DELETE ON SF1010 BY db_ddladmin),
ADD (SELECT, INSERT, UPDATE, DELETE ON SF1010 BY db_executor),

ADD (SELECT, INSERT, UPDATE, DELETE ON SF2010 BY db_datareader),
ADD (SELECT, INSERT, UPDATE, DELETE ON SF2010 BY db_datawriter),
ADD (SELECT, INSERT, UPDATE, DELETE ON SF2010 BY db_ddladmin),
ADD (SELECT, INSERT, UPDATE, DELETE ON SF2010 BY db_executor),

ADD (SELECT, INSERT, UPDATE, DELETE ON CT1010 BY db_datareader),
ADD (SELECT, INSERT, UPDATE, DELETE ON CT1010 BY db_datawriter),
ADD (SELECT, INSERT, UPDATE, DELETE ON CT1010 BY db_ddladmin),
ADD (SELECT, INSERT, UPDATE, DELETE ON CT1010 BY db_executor),

ADD (SELECT, INSERT, UPDATE, DELETE ON CT2010 BY db_datareader),
ADD (SELECT, INSERT, UPDATE, DELETE ON CT2010 BY db_datawriter),
ADD (SELECT, INSERT, UPDATE, DELETE ON CT2010 BY db_ddladmin),
ADD (SELECT, INSERT, UPDATE, DELETE ON CT2010 BY db_executor),

ADD (SELECT, INSERT, UPDATE, DELETE ON SA1010 BY db_datareader),
ADD (SELECT, INSERT, UPDATE, DELETE ON SA1010 BY db_datawriter),
ADD (SELECT, INSERT, UPDATE, DELETE ON SA1010 BY db_ddladmin),
ADD (SELECT, INSERT, UPDATE, DELETE ON SA1010 BY db_executor),

ADD (SELECT, INSERT, UPDATE, DELETE ON SA2010 BY db_datareader),
ADD (SELECT, INSERT, UPDATE, DELETE ON SA2010 BY db_datawriter),
ADD (SELECT, INSERT, UPDATE, DELETE ON SA2010 BY db_ddladmin),
ADD (SELECT, INSERT, UPDATE, DELETE ON SA2010 BY db_executor),

ADD (SELECT, INSERT, UPDATE, DELETE ON SB1010 BY db_datareader),
ADD (SELECT, INSERT, UPDATE, DELETE ON SB1010 BY db_datawriter),
ADD (SELECT, INSERT, UPDATE, DELETE ON SB1010 BY db_ddladmin),
ADD (SELECT, INSERT, UPDATE, DELETE ON SB1010 BY db_executor),

ADD (SELECT, INSERT, UPDATE, DELETE ON SRA010 BY db_datareader),
ADD (SELECT, INSERT, UPDATE, DELETE ON SRA010 BY db_datawriter),
ADD (SELECT, INSERT, UPDATE, DELETE ON SRA010 BY db_ddladmin),
ADD (SELECT, INSERT, UPDATE, DELETE ON SRA010 BY db_executor),

ADD (SELECT, INSERT, UPDATE, DELETE ON SRD010 BY db_datareader),
ADD (SELECT, INSERT, UPDATE, DELETE ON SRD010 BY db_datawriter),
ADD (SELECT, INSERT, UPDATE, DELETE ON SRD010 BY db_ddladmin),
ADD (SELECT, INSERT, UPDATE, DELETE ON SRD010 BY db_executor),

ADD (SELECT, INSERT, UPDATE, DELETE ON SRI010 BY db_datareader),
ADD (SELECT, INSERT, UPDATE, DELETE ON SRI010 BY db_datawriter),
ADD (SELECT, INSERT, UPDATE, DELETE ON SRI010 BY db_ddladmin),
ADD (SELECT, INSERT, UPDATE, DELETE ON SRI010 BY db_executor),

ADD (SELECT, INSERT, UPDATE, DELETE ON SX5010 BY db_datareader),
ADD (SELECT, INSERT, UPDATE, DELETE ON SX5010 BY db_datawriter),
ADD (SELECT, INSERT, UPDATE, DELETE ON SX5010 BY db_ddladmin),
ADD (SELECT, INSERT, UPDATE, DELETE ON SX5010 BY db_executor),

ADD (SELECT, INSERT, UPDATE, DELETE ON SXA010 BY db_datareader),
ADD (SELECT, INSERT, UPDATE, DELETE ON SXA010 BY db_datawriter),
ADD (SELECT, INSERT, UPDATE, DELETE ON SXA010 BY db_ddladmin),
ADD (SELECT, INSERT, UPDATE, DELETE ON SXA010 BY db_executor),

ADD (SELECT, INSERT, UPDATE, DELETE ON SB2010 BY db_datareader),
ADD (SELECT, INSERT, UPDATE, DELETE ON SB2010 BY db_datawriter),
ADD (SELECT, INSERT, UPDATE, DELETE ON SB2010 BY db_ddladmin),
ADD (SELECT, INSERT, UPDATE, DELETE ON SB2010 BY db_executor),

ADD (SELECT, INSERT, UPDATE, DELETE ON SD1010 BY db_datareader),
ADD (SELECT, INSERT, UPDATE, DELETE ON SD1010 BY db_datawriter),
ADD (SELECT, INSERT, UPDATE, DELETE ON SD1010 BY db_ddladmin),
ADD (SELECT, INSERT, UPDATE, DELETE ON SD1010 BY db_executor),

ADD (SELECT, INSERT, UPDATE, DELETE ON SD2010 BY db_datareader),
ADD (SELECT, INSERT, UPDATE, DELETE ON SD2010 BY db_datawriter),
ADD (SELECT, INSERT, UPDATE, DELETE ON SD2010 BY db_ddladmin),
ADD (SELECT, INSERT, UPDATE, DELETE ON SD2010 BY db_executor)
WITH (STATE = ON);